# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/vivado_2d_FFT/project_1.srcs/sources_1/bd/design_1/ip/design_1_fft2d_fixed_top_0_0/design_1_fft2d_fixed_top_0_0.xci
# IP: The module: 'design_1_fft2d_fixed_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_2d_FFT/project_1.srcs/sources_1/bd/design_1/ip/design_1_fft2d_fixed_top_0_0/constraints/fft2d_fixed_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fft2d_fixed_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/vivado_2d_FFT/project_1.srcs/sources_1/bd/design_1/ip/design_1_fft2d_fixed_top_0_0/design_1_fft2d_fixed_top_0_0.xci
# IP: The module: 'design_1_fft2d_fixed_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/vivado_2d_FFT/project_1.srcs/sources_1/bd/design_1/ip/design_1_fft2d_fixed_top_0_0/constraints/fft2d_fixed_top_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fft2d_fixed_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
